### ISSUE TITLE
errors when working offline

### ISSUE THREAD

**Issue by lyricalpolymath** [boxxa/meteor-polymer#2]
Hi Boxxa, again :)
I understand that you've simply forked the code from ecywin and simply updated the polymer version.. so you tell me if I should go ask the original author about this question.

The package throws an error when working offline:
this error happens also with the boxxa:polymer-elements package

```
I20150205-19:09:08.573(1)? installing polymer into public directory...
W20150205-19:09:08.683(1)? (STDERR) 
W20150205-19:09:08.683(1)? (STDERR) /Users/b/.meteor/packages/meteor-tool/.1.0.40.1jrw2w5++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:206
W20150205-19:09:08.683(1)? (STDERR)                                             throw(ex);
W20150205-19:09:08.684(1)? (STDERR)                                                   ^
W20150205-19:09:08.699(1)? (STDERR) Error: Failed to execute "git ls-remote --tags --heads git://github.com/Polymer/polymer.git", exit code of #128
W20150205-19:09:08.699(1)? (STDERR)     at Object.Future.wait (/Users/b/.meteor/packages/meteor-tool/.1.0.40.1jrw2w5++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:326:15)
W20150205-19:09:08.699(1)? (STDERR)     at Object.install (packages/meteor/helpers.js:119:1)
W20150205-19:09:08.699(1)? (STDERR)     at Package (packages/boxxa:polymer/boxxa:polymer.js:25:1)
W20150205-19:09:08.699(1)? (STDERR)     at /Users/b/Documents/Polymer/polymer-tutorial-meteor/.meteor/local/build/programs/server/packages/boxxa_polymer.js:50:4
W20150205-19:09:08.699(1)? (STDERR)     at /Users/b/Documents/Polymer/polymer-tutorial-meteor/.meteor/local/build/programs/server/packages/boxxa_polymer.js:57:3
W20150205-19:09:08.700(1)? (STDERR)     at /Users/b/Documents/Polymer/polymer-tutorial-meteor/.meteor/local/build/programs/server/boot.js:205:10
W20150205-19:09:08.700(1)? (STDERR)     at Array.forEach (native)
W20150205-19:09:08.700(1)? (STDERR)     at Function._.each._.forEach (/Users/b/.meteor/packages/meteor-tool/.1.0.40.1jrw2w5++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150205-19:09:08.700(1)? (STDERR)     at /Users/b/Documents/Polymer/polymer-tutorial-meteor/.meteor/local/build/programs/server/boot.js:116:5
W20150205-19:09:08.700(1)? (STDERR)     - - - - -
W20150205-19:09:08.700(1)? (STDERR)     at createError (/Users/b/.meteor/packages/boxxa_polymer/.0.5.4.znfoex++os+web.browser+web.cordova/npm/node_modules/bower/lib/util/createError.js:4:15)
W20150205-19:09:08.700(1)? (STDERR)     at ChildProcess.<anonymous> (/Users/b/.meteor/packages/boxxa_polymer/.0.5.4.znfoex++os+web.browser+web.cordova/npm/node_modules/bower/lib/util/cmd.js:102:21)
W20150205-19:09:08.700(1)? (STDERR)     at ChildProcess.emit (events.js:98:17)
W20150205-19:09:08.700(1)? (STDERR)     at maybeClose (child_process.js:756:16)
W20150205-19:09:08.700(1)? (STDERR)     at Socket.<anonymous> (child_process.js:969:11)
W20150205-19:09:08.701(1)? (STDERR)     at Socket.emit (events.js:95:17)
W20150205-19:09:08.701(1)? (STDERR)     at Pipe.close (net.js:465:12)
```

it seems that `localCache` is always empty

any ideas?
thanks

**Comment by boxxa** [comment]
The first run will pull in bower. Is this after you created the public/bower_components folder on first run and any future runs?

**Comment by lyricalpolymath** [comment]
in any run after the first, even after all the components have downloaded succesfully.

Don't you have the same problem?
I had to remove the package and write the <head> by hand to add the polyfills, to make it work

**Comment by boxxa** [comment]
I always run online, never offline. Will give this a shot later on and see if I can fix it.

**Comment by boxxa** [comment]
I gave it a run offline. I can not get this to happen. I install boxxa:polymer-elements and then run meteor. If loads the bower_components into public/. After that, I disable my internet connection and rerun meteor. I am able to run it without any issues with connectivity from local cache.
