### ISSUE TITLE
Polymer Throws an Error when initially adding the packages to Meteor.

### ISSUE THREAD

**Issue by romans127** [boxxa/meteor-polymer#6]
I've created the `public` , `server` , and `client` folders on a brand new meteor project and I'm receiving the following error. 

---

``` sh
W20150815-18:30:50.562(-7)? (STDERR) 
W20150815-18:30:50.562(-7)? (STDERR) /Users/ryanwatts/.meteor/packages/meteor-tool/.1.1.4.j9dzi4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150815-18:30:50.563(-7)? (STDERR)                                            throw(ex);
W20150815-18:30:50.563(-7)? (STDERR)                                                  ^
W20150815-18:30:50.602(-7)? (STDERR) Error: No tag found that was able to satisfy 1.0.0
W20150815-18:30:50.603(-7)? (STDERR)     at Object.install (packages/meteor/helpers.js:119:1)
W20150815-18:30:50.602(-7)? (STDERR)     at Object.Future.wait (/Users/ryanwatts/.meteor/packages/meteor-tool/.1.1.4.j9dzi4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150815-18:30:50.603(-7)? (STDERR)     at Package (packages/boxxa:polymer-elements/boxxa:polymer-elements.js:25:1)
W20150815-18:30:50.603(-7)? (STDERR)     at /Users/ryanwatts/Documents/Sites/MeteorApps/polymer/.meteor/local/build/programs/server/packages/boxxa_polymer-elements.js:50:4
W20150815-18:30:50.603(-7)? (STDERR)     at /Users/ryanwatts/Documents/Sites/MeteorApps/polymer/.meteor/local/build/programs/server/packages/boxxa_polymer-elements.js:57:3
W20150815-18:30:50.603(-7)? (STDERR)     at /Users/ryanwatts/Documents/Sites/MeteorApps/polymer/.meteor/local/build/programs/server/boot.js:222:10
W20150815-18:30:50.603(-7)? (STDERR)     at Array.forEach (native)
W20150815-18:30:50.603(-7)? (STDERR)     at Function._.each._.forEach (/Users/ryanwatts/.meteor/packages/meteor-tool/.1.1.4.j9dzi4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150815-18:30:50.603(-7)? (STDERR)     at /Users/ryanwatts/Documents/Sites/MeteorApps/polymer/.meteor/local/build/programs/server/boot.js:117:5
W20150815-18:30:50.604(-7)? (STDERR)     - - - - -
W20150815-18:30:50.604(-7)? (STDERR)     at createError (/Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/lib/util/createError.js:4:15)
W20150815-18:30:50.604(-7)? (STDERR)     at /Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/lib/core/resolvers/GitResolver.js:144:23
W20150815-18:30:50.604(-7)? (STDERR)     at /Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:1142:26
W20150815-18:30:50.604(-7)? (STDERR)     at _fulfilled (/Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:787:54)
W20150815-18:30:50.604(-7)? (STDERR)     at self.promiseDispatch.done (/Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:816:30)
W20150815-18:30:50.604(-7)? (STDERR)     at Promise.promise.promiseDispatch (/Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:749:13)
W20150815-18:30:50.604(-7)? (STDERR)     at /Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:509:49
W20150815-18:30:50.604(-7)? (STDERR)     at flush (/Users/ryanwatts/.meteor/packages/boxxa_polymer-elements/.1.0.0.1g50myd++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:108:17)
W20150815-18:30:50.604(-7)? (STDERR)     at process._tickCallback (node.js:442:13)
=> Couldn't spawn process: channel closed

```

**Comment by romans127** [comment]
Figured out the issue, however My reloads are extremely slow even with the created the client, server, and public folders.

**Comment by splendido** [comment]
out of curiosity, what was the issue?
...I'm getting the same error :(

**Comment by boxxa** [comment]
I think the install version changed. I apologize as I have moved away from Polymer so I have not updated this package but will try to look tomorrow.

**Comment by milanzigmond** [comment]
boxxa, why did you move away from Polymer? any particular reason?

I'm also getting the same issue http://prntscr.com/89ftci

**Comment by SPAHI4** [comment]
same issue

**Comment by boxxa** [comment]
Polymer Elements needs to be removed. That is for the 0.5.5 version of Meteor Polymer. The Polymer Paper is the elements that should work.

https://github.com/boxxa/meteor-polymer-paper

**Comment by SPAHI4** [comment]
@boxxa meteor-polymer-paper requires meteor-polymer

**Comment by boxxa** [comment]
Got it. I just duplicated this. Will clean it up now.
